### ISSUE TITLE
Can we save the map image in localstorage?

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/sapp-production-map#15]
It would be good to save the image in the browser because we do not have a backend yet

**Comment by olegkolner** [comment]
Yes, it works, through saving image's URL. Check it out - https://github.com/ScaleIT-Org/sapp-production-map/blob/dev/src/pages/home/home.ts

**Comment by frostyandy2k** [comment]
But wait, is the image itself saved ?  What happens if i close and reopen the browser?

**Comment by frostyandy2k** [comment]
But is the image data also saved?

**Comment by olegkolner** [comment]
Seems to be so. Have just tested it by loading an image by clicking "select map" button and afterwards the uploaded image was deleted from filesystem and browser was restarted. The app's page was opened with previously uploaded image.

**Comment by frostyandy2k** [comment]
Top!
