### ISSUE TITLE
Add checkbox in Menu in order to lock scrolling on the user page

### ISSUE THREAD

**Issue by frostyandy2k** [ScaleIT-Org/sapp-production-map#17]
When i click on the checkbox ("Disable Map Scroll"), I want to not be able to scroll the page.

Imagine the map is on a very big touch screen, if we scroll we move everything and it does not make a nice effect.

**Comment by olegkolner** [comment]
Done. https://github.com/ScaleIT-Org/sapp-production-map/commit/308bdaac06c7e2641638368d681e3d17a139a6f8
