### ISSUE TITLE
3. Requirement - upload map

### ISSUE THREAD

**Issue by olegkolner** [ScaleIT-Org/sapp-production-map#3]
A user have to be capable to upload a map. In this context "map" means a photo with a plan of some room.

**Comment by olegkolner** [comment]
Done. See https://github.com/ScaleIT-Org/sapp-production-map/tree/dev/src/pages/home

**Comment by frostyandy2k** [comment]
Don't forget that in order to finish, you need to merge with master. Create a pull request
